---
- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0-fpm
    - git

  ignore_errors: yes

  notify:
    - restart php7.0-fpm
    - restart nginx
